### ISSUE TITLE
Dirty groups data breaks the GET /challenges endpoint

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/legacy-challenge-migration-script#16]
We added the following to the ES query when the caller is not authenticated but because of dirty data (`null` and `undefined` string values) in ES, this makes the response always be an empty array.

```
{
   must_not: { exists: { field: 'groups' } }
}
```

This needs to be fixed here so we completely omit `null` and `undefined` values.

**Comment by rootelement** [comment]
I believe groups data on the backend is clean now, as Group UUIDs are looked up and only added if valid, and the challenge isn't migrated if the group is invalid. But I know that the groups: [] array is still added. Also, I believe you added a check on save/update in the challenge service:
https://github.com/topcoder-platform/legacy-challenge-migration-script/blob/master/src/services/challengeService.js#L48

So this can be closed, right @ThomasKranitsas ?
